<?php

/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array(
    'built_in_version' => '7.9.2.0',
    'acceptable_sugar_versions' => array(
        0 => '',
    ),
    'acceptable_sugar_flavors' => array(
        0 => 'PRO',
    ),
    'readme' => '',
    'key' => 'AS',
    'author' => 'Andrew Styles',
    'description' => 'Application Test',
    'icon' => '',
    'is_uninstallable' => true,
    'name' => 'Contacts: Horoscope Signs',
    'published_date' => '2017-12-02',
    'type' => 'module',
    'version' => '1.0.04',
    'remove_tables' => 'false',
);


$installdefs = array(
    'id' => 'as.application-test',
    'copy' => array(
        array(
            'from' => '<basepath>/custom/include/informed-dna',
            'to' => 'custom/include/informed-dna',
        ),
        array(
            'from' => '<basepath>/custom/modules/Contacts/clients/base/views/record',
            'to' => 'custom/modules/Contacts/clients/base/views/record',
        ),
        array(
            'from' => '<basepath>/custom/clients/base/api/HoroscopeApi.php',
            'to' => 'custom/clients/base/api/HoroscopeApi.php',
        ),
        array(
            'from' => '<basepath>/custom/Extension/modules/Contacts/Ext/LogicHooks/horoscope_hook.php',
            'to' => 'custom/Extension/modules/Contacts/Ext/LogicHooks/horoscope_hook.php',
        ),
        array(
            'from' => '<basepath>/custom/Extension/modules/Contacts/Ext/clients/base/views/record/search_google_button.php',
            'to' => 'custom/Extension/modules/Contacts/Ext/clients/base/views/record/search_google_button.php',
        ),
    ),
    'language' => array(
        array(
            'from' => '<basepath>/language/Contacts/en_us.lang.php',
            'to_module' => 'Contacts',
            'language' => 'en_us',
        ),
        array(
            'from' => '<basepath>/language/application/en_us.lang.php',
            'to_module' => 'application',
            'language' => 'en_us',
        ),
    ),
    'vardefs' => array(
        array(
            'from' => '<basepath>/vardefs/Contacts/as_contact_vardefs.php',
            'to_module' => 'Contacts',
        ),
    ),
);
